name = "Django smells"
description = "My custom Django rules, written in semgrep"
category = "language"

[analyzer]
  command = "python3 /app/analyze.py"

[build]
  image = "returntocorp/semgrep:0.77.0"
  steps = "cp -r ../../. /app"
